### ISSUE TITLE
snapshot artifact is not accessible

### ISSUE THREAD

**Issue by zhongdj** [sbtliquibase/sbt-liquibase-plugin#1]
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/github/sbtliquibase/sbt-liquibase-plugin_2.10_0.13/0.1.-SNAPSHOT/sbt-liquibase-plugin-0.1.-SNAPSHOT.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.sbtliquibase#sbt-liquibase-plugin;0.1.-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

Actually the URL: https://oss.sonatype.org/content/repositories/snapshots/com/github/sbtliquibase/ is not available.

**Comment by llinder** [comment]
I haven't setup publishing for Sonatype repos yet.  Its something I need as well and will get it setup as soon as I can.

**Comment by llinder** [comment]
master builds should be publishing to Sonatype OSS now.
