### ISSUE TITLE
com.github.sbtliquibase#sbt-liquibase;0.2.0: not found

### ISSUE THREAD

**Issue by AvihayTsayeg** [sbtliquibase/sbt-liquibase-plugin#11]
Hi,
I tried using the plugin and got this error
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.github.sbtliquibase#sbt-liquibase;0.2.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

```

my plugins.sbt contains
```
resolvers += "Sonatype releases" at "https://oss.sonatype.org/content/repositories/releases/"
resolvers += "sonatype-snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
resolvers += Resolver.url("artifactory", url("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)
resolvers += Resolver.mavenLocal
```

I tried looking in [sonatype](https://oss.sonatype.org/#nexus-search;quick~sbt-liquibase) for the artifact and did not find it.
my sbt version is 0.13.11

There might be an issue with the release artifact you are uploading
```
  if (isSnapshot.value)
    Some("snapshots" at nexus + "content/repositories/snapshots")
  else
    Some("releases"  at nexus + "service/local/staging/deploy/maven2")
```
[service/local/staging/deploy/maven2](https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/sbtliquibase/sbt-liquibase_2.10_0.13/) is protected by user password
should it be content/repositories/releases ?

Regards, Avihay

**Comment by LMnet** [comment]
Looks like @llinder haven't released 0.2.0 version after merging my pull request.

**Comment by llinder** [comment]
Sorry.  Published now.  It would be great to clean up the build process so tagging will make a release.  I will try to find some time to do that.

**Comment by AvihayTsayeg** [comment]
Thank you very much.

**Comment by AvihayTsayeg** [comment]
Hi,
I still can't reach the new artifact.

Avihay
