### ISSUE TITLE
Support for SBT 1.0...?

### ISSUE THREAD

**Issue by DanielaSfregola** [sbtliquibase/sbt-liquibase-plugin#17]
...any plan to support SBT 1.0?

I am happy to do the work if this project is still active and interested in releasing for 1.0

Cheers,
Daniela

**Comment by feoktant** [comment]
Hey, I am also interesting in this plugin for version 1.x. What do you think about fork of this project? Doesn't seem it is active anymore :'(

**Comment by DanielaSfregola** [comment]
I was about to start developing this, but I have realized that @permutive has already released a version of this plugin for sbt 1!

Have a look at https://github.com/permutive/sbt-liquibase-plugin

Thanks @permutive for releasing a version of this plugin for sbt 1 ❤️

**Comment by feoktant** [comment]
Wow, cool! Thank you for sharing this 👍
